#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-dwi2src

set -e  

dwi=$(jq -r .dwi config.json)
bval=$(jq -r .bvals config.json)
bvec=$(jq -r .bvecs config.json)

dwi_base_name=${dwi##*/}
echo $dwi_base_name

ln -s ${dwi} ${dwi_base_name}
time singularity exec -e docker://dsistudio/dsistudio dsi_studio --action=src --source=${dwi_base_name} --bval=${bval} --bvec=${bvec} --output=${dwi_base_name}.src.gz
