#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=1:00:00
#PBS -N dsi-studio-dwi2src

set -e  

dwi=$(jq -r .dwi config.json)
bval=$(jq -r .bvals config.json)
bvec=$(jq -r .bvecs config.json)


time singularity exec -e docker://dsistudio/dsistudio --action=src --source=${dwi} --bval=${bval} --bvec=${bvec} --output=${dwi}.src.gz
